title: UC&NL for DIY with love
email: support@unavlab.com
description: > 
  Underwater communication & navigation laboratory site for DIY projects  
baseurl: "" 
url: "http://diy.unavlab.com"
twitter_username: unavlab
github_username:  ucnl
